### PR TITLE
Changes for the latest pydicom

### PR DESCRIPTION
**Pull request by naggie**
Fixes https://github.com/patmun/pynetdicom/issues/31 and https://github.com/patmun/pynetdicom/issues/26

...aside from the dependent pydicom version number which has not changed yet.

As noted, https://github.com/cancan101/pynetdicom/commit/b41cfa12ab8f5831716edc4d05e502959ead6e93 may be the better fix, however a similar fix is also required for #31 .

Depends on if backwards compatibility is required or not. I would suggest not requiring it so long as pydicom releases a new version number which becomes a dependency.

### CODE REVIEW

**Comment by naggie** [comment]
This is more of a problem than I realised -- old (pip) versions of `pynetdicom` don't specify `pydicom` as a dependency. This means deployments with `virtualenv`+`pip` fail without installing `pydicom` first. This is exacerbated if you need to deploy versions before and after the rename.

Perhaps @cancan101 's fix is therefore more appropriate.

**Comment by cancan101** [comment]
I just [filed an issue with pydicom](https://github.com/darcymason/pydicom/issues/240) to please release to pypi with new package.

In the meantime you can also try: https://github.com/cancan101/pynetdicom-1/commit/a65b114e568656feea0f4f35e4ba461d04e2c76f (this is my new fork of this project). You will need to pip install with `--process-dependency-links`.

**Comment by naggie** [comment]
Excellent, thanks!

**Comment by cancan101** [comment]
This might also be helpful: https://github.com/pypa/pip/issues/1274

**Comment by naggie** [comment]
Looks like cancan101's PR has resolved this. Thanks

**Pull request closed without merging**
